export default {
  ACTION_CODE: {
    CREATE_MOD: "CREATE_MOD",
    DELETE_USER: "DELETE_USER",
    GET_USERS: "GET_USERS",
    CREATE_CV: "CREATE_CV",
    RECEIVE_MAIL: "RECEIVE_MAIL",
    CREATE_FEEDBACK: "CREATE_FEEDBACK",
    DELETE_FEEDBACK: "DELETE_FEEDBACK",
    VIEW_POSTS_NEED_ACCEPT: "VIEW_POSTS_NEED_ACCEPT",
    CREATE_POST: "CREATE_POST",
    UPDATE_POST: "UPDATE_POST",
    DELETE_POST: "DELETE_POST",
    ACCEPT_POST: "ACCEPT_POST",
    GET_COMPANY_POST: "GET_COMPANY_POST",
    ANALYSIS: "ANALYSIS",
    APPLY_JOB: "APPLY_JOB",
  },
  NOTIFICATIONS_TYPE: {
    SYSTEM: "SYSTEM",
    POST: "POST",
  },
};
